### ISSUE TITLE
What mash efficiency is assumed for the grain bill?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/opensourcery#4]
I'm punching the malts into my BeerAlchemy software with 70% mash efficiency, and the grain bill comes out to 1.048 OG.

To make it come out to 1.063 like the recipe here says, I have to set the mash efficiency to 92%. Is that what was used when making the recipe?

**Comment by mreid-moz** [comment]
The recipe claims:
> *Assumes BH Efficiency of 85%

**Comment by groovecoder** [comment]
Ah, I didn't know "BH" meant "mash" ... can we update the wording? Can we de-buzzword it a bit?

**Comment by mreid-moz** [comment]
I tried to de-buzzword a bit in #5

**Comment by groovecoder** [comment]
Fixed in https://github.com/mozilla/opensourcery/pull/5
